Unified publishing
MinecraftFreecam/Freecam pull request #140
Opened 2023-12-28 06:59 UTC by MattSturgeon

This PR implements shedanial's [unified-publishing](https://github.com/shedaniel/unified-publishing) plugin to streamline the curseforge/modrinth publishing process.

Publishing to GitHub is not covered by this PR. That may be better achieved as part of a CI/CD setup using GitHub Actions/Workflows.  
That said, [modpublisher](https://github.com/firstdarkdev/modpublisher) has built-in support for publishing GitHub releases as part of a unified publish task, so we could consider using that instead.

API tokens/keys must be set to actually do any publishing. These can either be gradle properties or environment variables.  
Personally, I'd probably set these as "user" gradle properties by creating a `gradle.properties` file in the [`GRADLE_USER_HOME`](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home) directory (`~/.gradle` or `C:\Users\<USERNAME>\.gradle`).  
Definitely **do not** put them in the project gradle properties, as these get committed to git :joy:!

Run using `gradlew publishUnified`.

**I haven't tested this**, since I don't have access to your tokens. It's possible I've misinterpreted what is meant by "modrinth id"; currently it's set to `"freecam"`.

When testing, I'd recommend changing the `releaseType` to alpha and changing `mod_version` to something like `"TEST"`.

Come to think of it, `releaseType` should probably be set as in `gradle.properties`... Any other feedback, questions, etc welcome.

Fixes #134

2024-01-21 13:58 UTC, MattSturgeon commented
@hashalite the next release could be a good opportunity to test this out? You could merge this locally and try using it without actually merging it on GitHub.

I'm happy to help worth through any teething issues with you on Discord, since I can't really test this myself without setting up Curseforge/Modrinth pages.

2024-02-01 03:29 UTC, hashalite requested changes

2024-02-01 03:29 UTC, hashalite commented on build.gradle
> +                    id = "freecam"
ID should be `XeEZ3fK2`

2024-02-01 10:03 UTC, MattSturgeon commented
I've ported over to [modpublisher](https://github.com/firstdarkdev/modpublisher) after our conversation earlier.

Once this is tested/refined further I'll squash the commits, but I've kept it separate for now in-case we decide to revert.

The issue with the fabric project not correctly configuring the requirements might be resolved by putting it in an `afterEvaluate` block (if it isn't already). Otherwise we can fallback to moving them to the root gradle script under an `if (project.name == "fabric")` block.

2024-02-02 07:56 UTC, hashalite approved these changes

2024-02-03 00:16 UTC, MattSturgeon commented
I've polished a bit further and implemented the ability to list additional supported mc versions using `supported_mc_versions` etc. `minecraft_version` is always marked as supported.

I was able to do some limited testing by setting a dummy api key & `debug=true`, everything appeared to work correctly.

The [issue we were experiencing](https://github.com/firstdarkdev/modpublisher/issues/6) with modrinth dependencies _should_ be resolved, but I can't test that.

The issue with `project.version` not being defined is now resolved.

2024-02-03 18:05 UTC, MattSturgeon commented
Bumped to modpublisher 2.0.5, so the [modrinth slug->id issue](https://github.com/firstdarkdev/modpublisher/issues/6) should be fully resolved now.

Worked correctly in my tests:

```json
"dependencies": [
    {
      "projectId": "P7dR8mSH",
      "dependencyType": "required"
    },
    {
      "projectId": "mOgUt4GM",
      "dependencyType": "optional"
    },
    {
      "projectId": "9s6osm5g",
      "dependencyType": "embedded"
    }
  ],
```

2024-02-04 05:34 UTC, hashalite approved these changes
Everything looks good, thank you!

2024-02-04 05:34 UTC, merged